// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Bookmark struct {
	ID        int64
	UserID    int64
	Title     string
	Url       string
	Icon      string
	Sort      int64
	CreatedAt int64
}

type Dbconn struct {
	ID          int64
	Name        string
	Engine      string
	Host        string
	Port        int64
	Username    string
	PasswordEnc string
	Database    string
	Params      string
	CreatedAt   int64
	UpdatedAt   int64
}

type File struct {
	ID        int64
	UserID    int64
	Name      string
	Stored    string
	Size      int64
	Mime      string
	CreatedAt int64
}

type LicenseApp struct {
	ID        int64
	Appid     string
	Secret    string
	Name      string
	Enabled   int64
	CreatedAt int64
}

type LicenseCard struct {
	ID          int64
	AppID       int64
	Card        string
	Hours       int64
	Domain      string
	ActivatedAt int64
	ExpiresAt   int64
	CreatedAt   int64
}

type Memory struct {
	K         string
	Content   string
	Project   string
	Tags      string
	WrittenBy string
	Revision  int64
	CreatedAt int64
	UpdatedAt int64
}

type PayOrder struct {
	ID              int64
	TradeNo         string
	OutTradeNo      string
	Channel         string
	Subject         string
	Money           int64
	Fee             int64
	Status          int64
	NotifyUrl       string
	ReturnUrl       string
	ClientIp        string
	Notified        int64
	NotifyAttempts  int64
	PaidAt          int64
	ExpiredAt       int64
	UpstreamTradeNo string
	GoodsKey        string
	Quantity        int64
	UnitPrice       int64
	Payurl          string
	Qrcode          string
	BuyerContact    string
	QueryPwd        string
	Cards           string
	CreatedAt       int64
}

type Proxy struct {
	ID            int64
	Ip            string
	Port          int64
	Protocols     string
	Anonymity     string
	Source        string
	RegionID      int64
	Latency       int64
	Speed         int64
	Uptime        int64
	Alive         int64
	FailCount     int64
	LastCheckedAt int64
	LastAliveAt   int64
	LastSeenAt    int64
	CreatedAt     int64
}

type ProxyKey struct {
	ID         int64
	Kkey       string
	Name       string
	RegionID   int64
	Enabled    int64
	UsedCount  int64
	LastUsedAt int64
	CreatedAt  int64
}

type ProxyRegion struct {
	ID     int64
	Code   string
	Name   string
	ZhName string
	Region string
	Slug   string
}

type ProxySync struct {
	ID         int64
	StartedAt  int64
	FinishedAt int64
	Status     string
	Source     string
	Total      int64
	Added      int64
	Removed    int64
	Updated    int64
	Detail     string
	Error      string
}

type Server struct {
	ID        int64
	Name      string
	Host      string
	Port      int64
	Username  string
	AuthType  string
	SecretEnc string
	Note      string
	CreatedAt int64
	UpdatedAt int64
}

type Session struct {
	Token     string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

type Setting struct {
	K string
	V string
}

type Share struct {
	ID        int64
	Code      string
	FileID    int64
	UserID    int64
	FileName  string
	ExpiresAt int64
	Downloads int64
	CreatedAt int64
}

type Tool struct {
	ID          int64
	Name        string
	Icon        string
	Url         string
	Description string
	Sort        int64
	Enabled     bool
}

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	Role         string
	Status       string
	CreatedAt    int64
	UpdatedAt    int64
}

type Vault struct {
	ID          int64
	UserID      int64
	Title       string
	Username    string
	PasswordEnc string
	Url         string
	Note        string
	TotpEnc     string
	CreatedAt   int64
	UpdatedAt   int64
}
