// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActivateLicenseCard(ctx context.Context, arg ActivateLicenseCardParams) error
	CountActiveSessions(ctx context.Context, expiresAt int64) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountBookmarksByUser(ctx context.Context, userID int64) (int64, error)
	CountDbconns(ctx context.Context) (int64, error)
	CountFilesAll(ctx context.Context) (int64, error)
	CountLicenseApps(ctx context.Context) (int64, error)
	CountLicenseCards(ctx context.Context, arg CountLicenseCardsParams) (int64, error)
	CountMemories(ctx context.Context) (int64, error)
	CountPayOrders(ctx context.Context, arg CountPayOrdersParams) (int64, error)
	CountProxies(ctx context.Context) (int64, error)
	CountProxiesAll(ctx context.Context) (int64, error)
	CountProxiesFiltered(ctx context.Context, arg CountProxiesFilteredParams) (int64, error)
	CountServers(ctx context.Context) (int64, error)
	CountTodayLogins(ctx context.Context) (int64, error)
	CountTools(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context, keyword sql.NullString) (int64, error)
	CountVaultByUser(ctx context.Context, userID int64) (int64, error)
	CreateLicenseApp(ctx context.Context, arg CreateLicenseAppParams) (int64, error)
	CreateLicenseCard(ctx context.Context, arg CreateLicenseCardParams) error
	CreatePayOrder(ctx context.Context, arg CreatePayOrderParams) (int64, error)
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) (int64, error)
	DeleteDbconn(ctx context.Context, id int64) (int64, error)
	DeleteDeadProxies(ctx context.Context, lastCheckedAt int64) (int64, error)
	DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error)
	DeleteLicenseApp(ctx context.Context, id int64) error
	DeleteLicenseCard(ctx context.Context, id int64) error
	DeleteMemory(ctx context.Context, k string) (int64, error)
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error
	DeleteProxy(ctx context.Context, id int64) error
	DeleteProxyApiKey(ctx context.Context, id int64) (int64, error)
	DeleteServer(ctx context.Context, id int64) (int64, error)
	DeleteSession(ctx context.Context, token string) error
	DeleteShare(ctx context.Context, arg DeleteShareParams) (int64, error)
	DeleteSharesByFile(ctx context.Context, fileID int64) error
	DeleteTool(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVault(ctx context.Context, arg DeleteVaultParams) (int64, error)
	FinishProxySync(ctx context.Context, arg FinishProxySyncParams) error
	GetDbconn(ctx context.Context, id int64) (Dbconn, error)
	GetFile(ctx context.Context, id int64) (File, error)
	GetLicenseAppByAppid(ctx context.Context, appid string) (LicenseApp, error)
	GetLicenseCard(ctx context.Context, arg GetLicenseCardParams) (LicenseCard, error)
	GetMemory(ctx context.Context, k string) (Memory, error)
	GetPayOrder(ctx context.Context, id int64) (PayOrder, error)
	GetPayOrderByOutNo(ctx context.Context, outTradeNo string) (PayOrder, error)
	GetPayOrderByTradeNo(ctx context.Context, tradeNo string) (PayOrder, error)
	GetProxyApiKey(ctx context.Context, kkey string) (ProxyKey, error)
	GetProxyRegionByCode(ctx context.Context, code string) (ProxyRegion, error)
	GetServer(ctx context.Context, id int64) (Server, error)
	GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error)
	GetSetting(ctx context.Context, k string) (string, error)
	GetShareByCode(ctx context.Context, code string) (GetShareByCodeRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetVault(ctx context.Context, arg GetVaultParams) (Vault, error)
	IncPayNotifyAttempts(ctx context.Context, id int64) error
	IncShareDownloads(ctx context.Context, code string) error
	InsertBookmark(ctx context.Context, arg InsertBookmarkParams) (int64, error)
	InsertDbconn(ctx context.Context, arg InsertDbconnParams) (int64, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (int64, error)
	InsertProxy(ctx context.Context, arg InsertProxyParams) (int64, error)
	InsertProxyApiKey(ctx context.Context, arg InsertProxyApiKeyParams) (int64, error)
	InsertProxySync(ctx context.Context, arg InsertProxySyncParams) (int64, error)
	InsertServer(ctx context.Context, arg InsertServerParams) (int64, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertShare(ctx context.Context, arg InsertShareParams) (int64, error)
	InsertTool(ctx context.Context, arg InsertToolParams) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	InsertVault(ctx context.Context, arg InsertVaultParams) (int64, error)
	LastProxyCheckAt(ctx context.Context) (interface{}, error)
	LicenseCardStats(ctx context.Context, arg LicenseCardStatsParams) (LicenseCardStatsRow, error)
	LicenseCardStatsAll(ctx context.Context, expiresAt int64) (LicenseCardStatsAllRow, error)
	ListBookmarks(ctx context.Context, userID int64) ([]Bookmark, error)
	ListDbconns(ctx context.Context) ([]Dbconn, error)
	ListEnabledTools(ctx context.Context) ([]Tool, error)
	ListFiles(ctx context.Context, userID int64) ([]File, error)
	ListLicenseApps(ctx context.Context) ([]ListLicenseAppsRow, error)
	ListLicenseCards(ctx context.Context, arg ListLicenseCardsParams) ([]LicenseCard, error)
	ListMemories(ctx context.Context, arg ListMemoriesParams) ([]Memory, error)
	ListPayOrders(ctx context.Context, arg ListPayOrdersParams) ([]PayOrder, error)
	ListPendingPayOrders(ctx context.Context) ([]PayOrder, error)
	ListProxiesDue(ctx context.Context, lastCheckedAt int64) ([]ListProxiesDueRow, error)
	ListProxiesFiltered(ctx context.Context, arg ListProxiesFilteredParams) ([]ListProxiesFilteredRow, error)
	ListProxyApiKeys(ctx context.Context) ([]ListProxyApiKeysRow, error)
	ListProxyKeys(ctx context.Context) ([]ListProxyKeysRow, error)
	ListProxyRegions(ctx context.Context) ([]ListProxyRegionsRow, error)
	ListProxySyncs(ctx context.Context, limit int64) ([]ProxySync, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListShares(ctx context.Context, userID int64) ([]Share, error)
	ListTools(ctx context.Context) ([]Tool, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVault(ctx context.Context, arg ListVaultParams) ([]Vault, error)
	LoginTrend(ctx context.Context, createdAt int64) ([]LoginTrendRow, error)
	MarkProxyAlive(ctx context.Context, arg MarkProxyAliveParams) error
	MarkProxyFailed(ctx context.Context, arg MarkProxyFailedParams) error
	MemoryProjects(ctx context.Context) ([]MemoryProjectsRow, error)
	PayDailyPaid(ctx context.Context, paidAt int64) ([]PayDailyPaidRow, error)
	PayOrderStats(ctx context.Context, createdAt int64) (PayOrderStatsRow, error)
	RandomProxies(ctx context.Context, arg RandomProxiesParams) ([]RandomProxiesRow, error)
	RecentPaidOrders(ctx context.Context, limit int64) ([]RecentPaidOrdersRow, error)
	SetPayNotified(ctx context.Context, id int64) error
	SetPayOrderQrcode(ctx context.Context, arg SetPayOrderQrcodeParams) error
	SetPayOrderStatus(ctx context.Context, arg SetPayOrderStatusParams) error
	SetPayOrderUpstream(ctx context.Context, arg SetPayOrderUpstreamParams) error
	TouchProxyApiKey(ctx context.Context, arg TouchProxyApiKeyParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (int64, error)
	UpdateDbconn(ctx context.Context, arg UpdateDbconnParams) (int64, error)
	UpdateLicenseApp(ctx context.Context, arg UpdateLicenseAppParams) error
	UpdateProxySeen(ctx context.Context, arg UpdateProxySeenParams) error
	UpdateServer(ctx context.Context, arg UpdateServerParams) (int64, error)
	UpdateTool(ctx context.Context, arg UpdateToolParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVault(ctx context.Context, arg UpdateVaultParams) (int64, error)
	UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error
	UpsertProxyRegion(ctx context.Context, arg UpsertProxyRegionParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
